name: Linters

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout project
      uses: actions/checkout@v5

    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install -U -r requirements_dev.txt
        pip install -U -e .

    - run: make ruff
    - run: make pylint
    - run: make mypy
