name: Test
on: ["push", "pull_request"]
jobs:
  test-py27:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout project files
      uses: actions/checkout@v5

    - name: Install python 2.7 with special action
      uses: LizardByte/actions/actions/setup_python@master
      with:
        python-version: '2.7'

    - name: Install dependencies
      run: |
        pip install -U -r requirements_dev.txt

    - name: Build project wheel and install
      run: |
        make build
        mv unicodec backup_unicodec
        mv dist/*.whl dist/unicodec-0.0.1-py2.py3-none-any.whl
        pip install -U "unicodec @ file://$(pwd)/dist/unicodec-0.0.1-py2.py3-none-any.whl"

    - name: Run tests
      run: |
        make test

  test-py3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:

    - name: Checkout project files
      uses: actions/checkout@v5

    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install -U -r requirements_dev.txt

    - name: Build project wheel and install
      run: |
        make build
        mv unicodec backup_unicodec
        mv dist/*.whl dist/unicodec-0.0.1-py2.py3-none-any.whl
        pip install -U "unicodec @ file://$(pwd)/dist/unicodec-0.0.1-py2.py3-none-any.whl"

    - name: Run tests
      run: |
        make test
